### ISSUE TITLE
HTTPSConnectionPool Error while reading data from Zendesk using Zenpy

### ISSUE THREAD

**Issue by jayesh423** [facetoe/zenpy#164]
Hi facetoe,

I am backfilling tickets data from Zendesk using zenpy. I am using tickets.incremental and saving 1000 records after each response. It runs fine for an hour and it writes data as well. However, it fails after that. I tried running it couple of time locally and it failed after reading different no. of rows.

Not sure what is wrong. I've included stack trace here. Can you please help out? 

Error:
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)': /api/v2/incremental/tickets.json?include=metric_sets%2Cdates&start_time=1341583775
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)': /api/v2/incremental/tickets.json?include=metric_sets%2Cdates&start_time=1341583775
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)': /api/v2/incremental/tickets.json?include=metric_sets%2Cdates&start_time=1341583775
Traceback (most recent call last):
  File "C:/ZendeskTest.py", line 247, in __call__
    startDate, recordCount = self.loadIncrementalData(startDate,zendeskObj,columnList, schema)
  File "C:/ZendeskTest.py", line 151, in loadIncrementalData
    for i, result in enumerate(result_generator):
  File "C:\Python27\lib\site-packages\zenpy\lib\generator.py", line 35, in next
    self.handle_pagination()
  File "C:\Python27\lib\site-packages\zenpy\lib\generator.py", line 44, in handle_pagination
    self._response_json = self.get_next_page()
  File "C:\Python27\lib\site-packages\zenpy\lib\generator.py", line 100, in get_next_page
    return super(ZendeskResultGenerator, self).get_next_page()
  File "C:\Python27\lib\site-packages\zenpy\lib\generator.py", line 61, in get_next_page
    response = self.response_handler.api._get(url, raw_response=True)
  File "C:\Python27\lib\site-packages\zenpy\lib\api.py", line 81, in _get
    response = self._call_api(self.session.get, url, timeout=self.timeout)
  File "C:\Python27\lib\site-packages\zenpy\lib\api.py", line 102, in _call_api
    response = http_method(url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 521, in get
Processing took: 1:37:29.710000
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 506, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='rockstarsupport.zendesk.com', port=443): Max retries exceeded with url: /api/v2/incremental/tickets.json?include=metric_sets%2Cdates&start_time=1341583775 (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))

**Comment by facetoe** [comment]
Hi @jayesh423, is the amount of time it takes to throw the error pretty constant, or does it sometimes fail after only a few minutes? Also are you writing to the API as well as reading?

**Comment by jayesh423** [comment]
Thanks @facetoe for quick response.
processing time is not constant. It runs for more than an hour without any issues.
I am only reading data.

**Comment by jayesh423** [comment]
is the amount of time it takes to throw the error pretty constant--> No
does it sometimes fail after only a few minutes? --> No. It is running for at least an hours in last 4 trials
Also are you writing to the API as well as reading? --> Just reading data from Zendesk

**Comment by facetoe** [comment]
Hmm, looking at the error it seems likely that this is an issue with Zendesk itself. One theory for what is going on might be that one of the Zendesk servers has a misconfigured SSL certificate, and you only hit this server very rarely. That would explain why it takes so long for the error to appear.

If you enable logging we can test this theory as Zenpy dumps the headers on exceptions talking to the API, and Zendesk includes the `X-Zendesk-Origin-Server` header which shows which of their servers handled the request, as well as some other useful info for debugging.

**Comment by Xerrion** [comment]
I am also encountering this bug. I would like to contribute with a log on fail. I have set up a custom logger for my project and zenpy doesn't log to it,, is there a way to connect it to mine?

**Comment by Xerrion** [comment]
I am also encountering this bug. I would like to contribute with a log on fail. I have set up a custom logger for my project and zenpy doesn't log to it,, is there a way to connect it to mine?

Heres my traceback

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 598, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='dsg.zendesk.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "app.py", line 19, in main
    tickets.do_export()
  File "/home/xerrion/projects/helphouse-zendesk-backup-service/export/tickets.py", line 23, in do_export
    for ticket in client.tickets.incremental(start_time=start_time, include=["users", "comment_count"]):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 156, in __next__
    return self.next()
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 45, in next
    self.handle_pagination()
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 54, in handle_pagination
    self._response_json = self.get_next_page(page_num=page_num, page_size=page_size)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 185, in get_next_page
    return super(ZendeskResultGenerator, self).get_next_page(page_num, page_size)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 71, in get_next_page
    response = self.response_handler.api._get(url, raw_response=True, params=params)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/api.py", line 112, in _get
    response = self._call_api(self.session.get, url, timeout=self.timeout, **kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/api.py", line 131, in _call_api
    response = self._ratelimit(http_method=http_method, url=url, **kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/api.py", line 173, in _ratelimit
    response = http_method(url, **kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/models.py", line 757, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='dsg.zendesk.com', port=443): Read timed out.
```

**Comment by Xerrion** [comment]
I am also encountering this bug. I would like to contribute with a log on fail. I have set up a custom logger for my project and zenpy doesn't log to it,, is there a way to connect it to mine?

I am also only reading data from Zendesk through the `incremental` endpoint, and then writing to a local disk.

Here's my traceback

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 360, in _error_catcher
    yield
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 666, in read_chunked
    self._update_chunk_length()
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 598, in _update_chunk_length
    line = self._fp.fp.readline()
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 490, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 694, in read_chunked
    self._original_response.close()
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/urllib3/response.py", line 365, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='d3v-helphouse.zendesk.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "app.py", line 19, in main
    tickets.do_export()
  File "/home/xerrion/projects/helphouse-zendesk-backup-service/export/tickets.py", line 23, in do_export
    for ticket in client.tickets.incremental(start_time=start_time, include=["users", "comment_count"]):
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 156, in __next__
    return self.next()
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 45, in next
    self.handle_pagination()
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 54, in handle_pagination
    self._response_json = self.get_next_page(page_num=page_num, page_size=page_size)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 185, in get_next_page
    return super(ZendeskResultGenerator, self).get_next_page(page_num, page_size)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/generator.py", line 71, in get_next_page
    response = self.response_handler.api._get(url, raw_response=True, params=params)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/api.py", line 112, in _get
    response = self._call_api(self.session.get, url, timeout=self.timeout, **kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/api.py", line 131, in _call_api
    response = self._ratelimit(http_method=http_method, url=url, **kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/zenpy/lib/api.py", line 173, in _ratelimit
    response = http_method(url, **kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/xerrion/projects/envs/helphouse-zendesk-backup-service/lib/python3.6/site-packages/requests/models.py", line 757, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='d3v-helphouse.zendesk.com', port=443): Read timed out.
```

**Comment by facetoe** [comment]
This looks like a different error. In your case the connection is just timing out, which could be a network issue between you and Zendesk, or they could be taking too long to provide a response.
