### ISSUE TITLE
updating custom field in condition of a view  is giving errors 

### ISSUE THREAD

**Issue by Axeish** [facetoe/zenpy#225]
I have a view which has following condition:

```
 'all': [
{u'operator': u'is', u'field': u'custom_fields_46607328', u'value': u'abc'}, 
{u'operator': u'less_than', u'field': u'NEW', u'value': u'16'}, 
{u'operator': u'is_not', u'field': u'group_id', u'value': u'36556468'}

],
'any': [
{u'operator': u'is', u'field': u'custom_fields_46607348', u'value': u'VALUE1'}
], 
```

I am trying to change/add Any part with this value 

`{u'operator': u'is', u'field': u'custom_fields_46607348', u'value': u'VALUE2'}`

Although on update I am getting error as below. **I definitely have Group mentioned so not sure what is wrong here** 

`    raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"details": {"base": [{"description": "View must test for at least <strong>one</strong> of the following ticket properties in the ALL conditions section: Status, Type, Group, Assignee, Requester."}]}, "description": "Record validation errors", "error": "RecordInvalid"}`

**Comment by facetoe** [comment]
Can you post the snippet that triggers the error and also let me know which version of Zenpy you are using?

**Comment by Axeish** [comment]
I am using zenpy=2.0.2


here is the snippet : 

```
Traceback (most recent call last):
  File "./modifyview.py", line 83, in <module>
    update_view= fgzenpy_client.views.update(view2)
  File "/Users/ashishkumar/MyProjects/JC_script/zenfile/jc/lib/python2.7/site-packages/zenpy/lib/api.py", line 423, in update
    return CRUDRequest(self).put(api_objects)
  File "/Users/ashishkumar/MyProjects/JC_script/zenfile/jc/lib/python2.7/site-packages/zenpy/lib/request.py", line 99, in put
    return self.api._put(url, payload=payload)
  File "/Users/ashishkumar/MyProjects/JC_script/zenfile/jc/lib/python2.7/site-packages/zenpy/lib/api.py", line 90, in _put
    response = self._call_api(self.session.put, url, json=self._serialize(payload), timeout=self.timeout)
  File "/Users/ashishkumar/MyProjects/JC_script/zenfile/jc/lib/python2.7/site-packages/zenpy/lib/api.py", line 135, in _call_api
    self._check_response(response)
  File "/Users/ashishkumar/MyProjects/JC_script/zenfile/jc/lib/python2.7/site-packages/zenpy/lib/api.py", line 274, in _check_response
    raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"details": {"base": [{"description": "View must test for at least <strong>one</strong> of the following ticket properties in the ALL conditions section: Status, Type, Group, Assignee, Requester."}]}, "description": "Record validation errors", "error": "RecordInvalid"}
```

**Comment by facetoe** [comment]
OK I think I have fixed this. Can you test and let me know if you still encounter these errors?
