### ISSUE TITLE
Support for Permanently Delete User API (GDPR related)

### ISSUE THREAD

**Issue by MrPGworks** [facetoe/zenpy#244]
Hi,

Looking forward to the support of the following endpoint:
https://developer.zendesk.com/rest_api/docs/core/users#permanently-delete-user

Keep going. It's an helpful wrapper for the work with Zendesk.

Best,
Pascal

**Comment by facetoe** [comment]
Yep this is is straightforward to add, I'll implement it soon.

**Comment by MrPGworks** [comment]
I am getting the following error:

Traceback (most recent call last):
  File "/Users/gdpr/gdpr-messaging/GDPR_removal.py", line 89, in <module>
    zenpy_client.users.permanently_delete(getuser)
  File "/Users/gdpr/Library/Python/2.7/lib/python/site-packages/zenpy/lib/util.py", line 110, in inner
    return func(*new_args, **new_kwargs)
  File "/Users/gdpr/Library/Python/2.7/lib/python/site-packages/zenpy/lib/api.py", line 781, in permanently_delete
    url = self._build_url(self.endpoint.permanently_delete(id=user))
AttributeError: 'PrimaryEndpoint' object has no attribute 'permanently_delete'

Could you have a look, please?

**Comment by facetoe** [comment]
Huh, dunno how I managed that. Give it a go now.
