### ISSUE TITLE
Object of type CcEvent is not JSON serializable.

### ISSUE THREAD

**Issue by gitlech** [facetoe/zenpy#284]
I was downloading all Audits data and when trying to serialize to a JSON file I got a TypeError: Object of type CcEvent is not JSON serializable.

Any idea what causes this or if there is a workaround?

Download Function:
```python
def download_audits_incremental(self, zenpy_client, *args, **kwargs):
    audits = {'audits': []}
    for ticket_id in sorted([ticket.id for ticket in zenpy_client.tickets.incremental(*args, **kwargs)]):
        for audit in zenpy_client.tickets.audits(ticket=ticket_id):
            audit_dict = audit.to_dict()
            audits['audits'].append(audit_dict)
    response = audits['audits']
    return response
```

JSON Function:
```python
with open(target_file, 'w') as target_file:
    json.dump(response, target_file, indent=4, ensure_ascii=False)
```

Error:
> 2018-12-12 16:06:26 - (DEBUG) - urllib3.connectionpool - https://xyz.zendesk.com:443 "GET /api/v2/tickets/280644/audits.json HTTP/1.1" 200 None
2018-12-12 16:06:27 - (DEBUG) - urllib3.connectionpool - https://xyz.zendesk.com:443 "GET /api/v2/tickets/280645/audits.json HTTP/1.1" 200 None
2018-12-12 16:06:35 - (INFO) - ZendeskDownloader - Serializing response for audits to disk -> /xyz/data/zendesk/downloader/temp/20181211_zendesk_audits_delta.json.
Traceback (most recent call last):
  File "/xyz/python/zendesk/zendesk_downloader.py", line 364, in <module>
    main()
  File "/xyz/python/zendesk/zendesk_downloader.py", line 357, in main
    dwh.run()
  File "/xyz/python/zendesk/zendesk_downloader.py", line 306, in run
    self.run_delta(zenpy_client, file_date, download_date_list)
  File "/xyz/python/zendesk/zendesk_downloader.py", line 251, in run_delta
    self.response_to_json(file_date, 'de', data_dict, endpoint, 'delta')
  File "/xyz/python/zendesk/zendesk_downloader.py", line 140, in response_to_json
    json.dump(response, target_file, indent=4, ensure_ascii=False)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type CcEvent is not JSON serializable

**Comment by facetoe** [comment]
Hi, 

Instead of `audit.to_dict()` try `audit.to_json()`. That will handle the serialization correctly.

Hope this helps!

**Comment by fmartingr** [comment]
To anyone coming here for the same issue but needing a serialized `dict` instead of a JSON text, you can use `obj.to_dict(serialize=True)` to get a `dict` object with only native python types in nested values.
Can you confirm this @facetoe ?

**Comment by facetoe** [comment]
Alternatively, you can use: 

```python
obj.to_dict()
```

When passing `serialize=True`, that tells Zenpy we are sending the object off to Zendesk and it will only include attributes of the object that have been modified (and the id).

**Comment by fmartingr** [comment]
yeah, but as this issue explains, if you use `audit.to_dict()` you get a `dict` object that contains non-native python types (`CCEvent`). The way I solved it is using `json.loads(audit.to_dict())` but it's less than ideal, my question is, should we expect `to_dict` to return native types only? (Because I did)

My use case is to store tickets in a database, I convert them to dict and store them on a JSONField or NoSQL database and this behaviour broke my workflow (until I added the JSON step).

**Comment by facetoe** [comment]
Which version of Zenpy are you using?

**Comment by fmartingr** [comment]
`zenpy==2.0.8`

**Comment by facetoe** [comment]
I'm unable to replicate this with the following code:

```python
for audit in zenpy_client.tickets.audits(ticket=6568):
    print(json.dumps(audit.to_dict(), indent=2))
```

The ticket seems to have the CcEvent:

```
  "events": [
    {
      "body": "asdasdsadas", 
      "plain_body": "asdasdsadas", 
      "attachments": [], 
      "audit_id": 547767678292, 
      "id": 547767678352, 
      "author_id": 116514121092, 
      "type": "Comment", 
      "public": true, 
      "html_body": "<div class=\"zd-comment\">asdasdsadas<br>\n</div>"
    }, 
    {
      "body": "You are registered as a CC on this request ({{ticket.id}}). Reply to this email to add a comment to the request.\n\n{{ticket.comments_formatted}}", 
      "type": "Cc", 
      "id": 547767679552, 
      "recipients": [
        368574752232
      ]
    }
  ]
```

Can you post a snippet that triggers the issue? Also the JSON returned from Zendesk would be useful as well.

**Comment by fmartingr** [comment]
Sorry, I used the `audit.to_dict()` as an example, my problem comes from the `Metadata` object (which contains some `ccs` key if I remember well). I can't give you more information right now, but I can make some tests again tomorrow morning (GMT+1) and give you more information.

**Comment by fmartingr** [comment]
Hey @facetoe sorry about the delay!

This is a sample output from an `audit.to_dict()`, I've removed the unnecessary keys:

``` javascript
{
    "author_id": 1,
    "created_at": "2018-12-19T23:38:59Z",
    "events": [],
    "id": 1,
    "ticket_id": 1,
    "metadata": {
        "custom": {},
        "system": {
            "client": "sailthru.com",
            "ip_address": "1",
            "latitude": None,
            "location": None,
            "longitude": None,
            "message_id": "<>",
            "raw_email_identifier": "",
            "json_email_identifier": "",
            "ccs": [CcEvent(id=None)],
        },
    },
}
```

**Comment by facetoe** [comment]
OK `to_dict()` should always return Python objects now. Let me know if you run into any issues.

**Comment by fmartingr** [comment]
Thanks a lot @facetoe, I'm going to take a look :+1:

**Comment by fmartingr** [comment]
@facetoe I just downloaded the dataset that had issues without errors, thanks again!
Please ping me when you release this to pypi to update our dependencies accodingly :+1:

**Comment by facetoe** [comment]
All good. I just released a new version to PyPi  - https://github.com/facetoe/zenpy/releases/tag/2.0.9
