### ISSUE TITLE
Strange error on zenpy_client.help_center.attachments.create_unassociated

### ISSUE THREAD

**Issue by insspb** [facetoe/zenpy#306]
`question = 'img/16926695267.png'` - path to image
```python
In[2]: from functions.auth import zenpy_client
In[3]: question = 'img/16926695267.png'
In[4]: zenpy_client.help_center.attachments.create_unassociated(question, inline=True)
DEBUG - POST: https://hidden.zendesk.com/api/v2/help_center/articles/attachments.json - {'json': {}, 'timeout': 60.0, 'headers': None, 'files': {'inline': (None, True), 'file': <_io.BufferedReader name='img/16926695267.png'>}}
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-be8053c1d689>", line 1, in <module>
    zenpy_client.help_center.attachments.create_unassociated(question, inline=True)
  File "/venv/src/zenpy/zenpy/lib/api.py", line 1874, in create_unassociated
    inline=inline)
  File "/venv/src/zenpy/zenpy/lib/request.py", line 523, in post
    return self.api._post(url, payload={}, files=dict(inline=(None, inline), file=file))
  File "/venv/src/zenpy/zenpy/lib/api.py", line 100, in _post
    **kwargs)
  File "/venv/src/zenpy/zenpy/lib/api.py", line 133, in _call_api
    response = http_method(url, **kwargs)
  File "/venv/lib/python3.6/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/venv/lib/python3.6/site-packages/requests/sessions.py", line 504, in request
    prep = self.prepare_request(req)
  File "/venv/lib/python3.6/site-packages/requests/sessions.py", line 436, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/venv/lib/python3.6/site-packages/requests/models.py", line 305, in prepare
    self.prepare_body(data, files, json)
  File "/venv/lib/python3.6/site-packages/requests/models.py", line 499, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/venv/lib/python3.6/site-packages/requests/models.py", line 158, in _encode_files
    fdata = fp.read()
AttributeError: 'bool' object has no attribute 'read'
```

Under investigation now.

**Comment by insspb** [comment]
Same in normal endpoint
```pyton
In[2]: from zenpy.lib.api_objects.help_centre_objects import Article
In[3]: from functions.auth import zenpy_client
In[4]: article = Article(id=360019142813)
In[5]: question = 'img/16926695267.png'
In[6]: import os
In[7]: os.path.isfile(question)
Out[7]: True
In[8]: post = zenpy_client.help_center.attachments.create(article=article, attachment=question)
DEBUG - POST: https://hidden.zendesk.com/api/v2/help_center/articles/360019142813/attachments.json - {'json': {}, 'timeout': 60.0, 'headers': None, 'files': {'inline': (None, False), 'file': <_io.BufferedReader name='img/16926695267.png'>}}
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-d3900d81a9d8>", line 1, in <module>
    post = zenpy_client.help_center.attachments.create(article=article, attachment=question)
  File "/venv/src/zenpy/zenpy/lib/util.py", line 110, in inner
    return func(*new_args, **new_kwargs)
  File "/venv/src/zenpy/zenpy/lib/api.py", line 1867, in create
    content_type=content_type)
  File "/venv/src/zenpy/zenpy/lib/request.py", line 523, in post
    return self.api._post(url, payload={}, files=dict(inline=(None, inline), file=file))
  File "/venv/src/zenpy/zenpy/lib/api.py", line 100, in _post
    **kwargs)
  File "/venv/src/zenpy/zenpy/lib/api.py", line 133, in _call_api
    response = http_method(url, **kwargs)
  File "/venv/lib/python3.6/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/venv/lib/python3.6/site-packages/requests/sessions.py", line 504, in request
    prep = self.prepare_request(req)
  File "/venv/lib/python3.6/site-packages/requests/sessions.py", line 436, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/venv/lib/python3.6/site-packages/requests/models.py", line 305, in prepare
    self.prepare_body(data, files, json)
  File "/venv/lib/python3.6/site-packages/requests/models.py", line 499, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "/venv/lib/python3.6/site-packages/requests/models.py", line 158, in _encode_files
    fdata = fp.read()
AttributeError: 'bool' object has no attribute 'read'
```

**Comment by insspb** [comment]
Works with code before PR #292
