### ISSUE TITLE
Help Center - You passed an invalid value for the sort_by attribute. The endpoint must specify a locale in order to sort by titles

### ISSUE THREAD

**Issue by Xerrion** [facetoe/zenpy#331]
I am trying to copy one Help Center to another. It works just fine until I hit a specific article.
I first create all the categories and then the sections inside those, and then the articles contained in the old instance in the sections.

My code is as following

```
def copy_help_center():
    # Create New Categories
    categories = old_client.help_center.categories()
    for category in categories:
        new_category = new_client.help_center.categories.create(
            Category(
                name=category.name,
                description=category.description,
                locale="en-us",
                created_at=category.created_at,
                updated_at=category.updated_at,
            )
        )

        # Create New Sections in Categories
        sections = old_client.help_center.categories.sections(category_id=category.id)
        for section in sections:
            new_section = new_client.help_center.sections.create(
                Section(
                    name=section.name,
                    category_id=new_category.id,
                    description=category.description,
                    locale="en-us",
                    created_at=section.created_at,
                    updated_at=section.updated_at,
                )
            )

            # Create New Articles in Sections
            articles = old_client.help_center.sections.articles(section=section)
            for article in articles:
                new_article = new_client.help_center.articles.create(
                    section=new_section.id,
                    article=Article(
                        name=article.name,
                        body=article.body,
                        locale="en-us",
                        title=article.title,
                        section_id=new_section.id,
                        created_at=article.created_at,
                        updated_at=article.updated_at,
                    ),
                )
                print(new_article.to_dict(serialize=True))
```

Traceback from stdout:
```
Traceback (most recent call last):
  File "/home/xerrion/projects/import-eurekos-file/import_try_2.py", line 236, in <module>
    copy_help_center()
  File "/home/xerrion/projects/import-eurekos-file/import_try_2.py", line 216, in copy_help_center
    articles = old_client.help_center.sections.articles(section=section)
  File "/home/xerrion/projects/envs/import-eurekos-file/lib/python3.6/site-packages/zenpy/lib/util.py", line 110, in inner
    return func(*new_args, **new_kwargs)
  File "/home/xerrion/projects/envs/import-eurekos-file/lib/python3.6/site-packages/zenpy/lib/api.py", line 1815, in articles
    return self._query_zendesk(self.endpoint.articles, 'article', id=section)
  File "/home/xerrion/projects/envs/import-eurekos-file/lib/python3.6/site-packages/zenpy/lib/api.py", line 257, in _query_zendesk
    return self._get(url=self._build_url(endpoint(*endpoint_args, **endpoint_kwargs)))
  File "/home/xerrion/projects/envs/import-eurekos-file/lib/python3.6/site-packages/zenpy/lib/api.py", line 112, in _get
    response = self._call_api(self.session.get, url, timeout=self.timeout, **kwargs)
  File "/home/xerrion/projects/envs/import-eurekos-file/lib/python3.6/site-packages/zenpy/lib/api.py", line 149, in _call_api
    self._check_response(response)
  File "/home/xerrion/projects/envs/import-eurekos-file/lib/python3.6/site-packages/zenpy/lib/api.py", line 288, in _check_response
    raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"error": {"title": "Invalid attribute", "message": "You passed an invalid value for the sort_by attribute. The endpoint must specify a locale in order to sort by titles"}}
```
A debug log with Zenpy messages are attached

[my-2019-05-15.log](https://github.com/facetoe/zenpy/files/3182687/my-2019-05-15.log)

**Comment by facetoe** [comment]
Hmmm this is a strange one. Are you able to make the `/api/v2/help_center/sections/360003398494/articles.json` successfully with curl? That message doesn't make much sense as no sort_by param was passed by the looks of it.

**Comment by Xerrion** [comment]
When I do a clean GET request to that endpoint I get the same error, but if I manually set "locale": "en-us" or "sort_by": "updated_at" it works just fine. If I send an anonymous request. I get this in the response body (All articles are only visible to signed-in users)

**Comment by facetoe** [comment]
Are you able to `curl` other articles without error, or do they all fail in the same way?

**Comment by Xerrion** [comment]
I am able to `curl` other sections fine, it's only that one that fails. Would I be able to modify the request so that I can set a `locale` or `sort_by`?

**Comment by facetoe** [comment]
> if I manually set "locale": "en-us"

Is this in the Section object? Or a param? Can you post the `curl` command that works?

It might be possible to modify the request.

**Comment by Xerrion** [comment]
```

**Comment by Xerrion** [comment]
It's a param, the following `curl`s work fine for that one.
```
curl --request GET \
  --url 'https://eurekos.zendesk.com/api/v2/help_center/sections/360003398494/articles.json?sort_by=updated_at' \
  --header 'authorization: Basic *************************************************'
```
or 
```
curl --request GET \
  --url 'https://eurekos.zendesk.com/api/v2/help_center/sections/360003398494/articles.json?locale=en-us' \
  --header 'authorization: Basic *************************************************'
``` 
It's this line that is failing `articles = old_client.help_center.sections.articles(section=section)`

**Comment by facetoe** [comment]
The patch in https://github.com/facetoe/zenpy/tree/issue-331 should do the trick (https://github.com/facetoe/zenpy/compare/issue-331).

**Comment by Xerrion** [comment]
Thanks you're a life saver!
