### ISSUE TITLE
API Exception accessing Author object in audit when audit caused by automation 

### ISSUE THREAD

**Issue by amjadtalib** [facetoe/zenpy#356]
Hi I'm seeing the following stack trace when calling `audit.author` for a ticket where the `audit` object had the following (sorted) JSON attribute: 
```json
{
  "author_id": -1,
  "created_at": "2019-08-29T12:34:14Z",
  ...
}
```

```python
Traceback (most recent call last):
  File "/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-47d41864eb6f>", line 1, in <module>
    audit.author
  File "/lib/python2.7/site-packages/zenpy/lib/api_objects/__init__.py", line 317, in author
    return self.api._get_user(self.author_id)
  File "/lib/python2.7/site-packages/zenpy/lib/api.py", line 324, in _get_user
    return self._query_zendesk(EndpointFactory('users'), 'user', id=user_id)
  File "/lib/python2.7/site-packages/zenpy/lib/api.py", line 257, in _query_zendesk
    return self._get(url=self._build_url(endpoint(*endpoint_args, **endpoint_kwargs)))
  File "/lib/python2.7/site-packages/zenpy/lib/api.py", line 112, in _get
    response = self._call_api(self.session.get, url, timeout=self.timeout, **kwargs)
  File "/lib/python2.7/site-packages/zenpy/lib/api.py", line 149, in _call_api
    self._check_response(response)
  File "/lib/python2.7/site-packages/zenpy/lib/api.py", line 288, in _check_response
    raise APIException(json.dumps(_json), response=response)
APIException: {"error": {"message": "You passed an invalid value for the id attribute. Invalid parameter: id must be greater than or equal to 0", "title": "Invalid attribute"}}
```

I checked the ticket and it turns out this audit was performed by an automation and the `Events ` view of the ticket shows the agent as Zendesk. 

I assume this applies to all automation audits, but I'm wondering if zenpy can factor for this without requiring separate code logic.

**Comment by lukeburden** [comment]
ZenPy would ideally detect this case, and add a dummy author object such that `comment.author` can resolve without hitting the network.

**Comment by facetoe** [comment]
Unfortunately don't have time to look at this right now, but should probably just return None in this case.

**Comment by facetoe** [comment]
Closing as doesn't seem to be an ongoing issue.

**Comment by facetoe** [comment]
Oops wrong issue
