### ISSUE TITLE
api search fails with python-3.7

### ISSUE THREAD

**Issue by netllama** [facetoe/zenpy#367]
```
>>> sp = {'type': 'organization', 'id': 9}
>>> o9 = api.search(sp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/netllama/nflx-git/oca-mgmt/venv/lib/python3.7/site-packages/zenpy/lib/api.py", line 321, in __call__
    return self._query_zendesk(self.endpoint, self.object_type, *args, **kwargs)
  File "/home/netllama/nflx-git/oca-mgmt/venv/lib/python3.7/site-packages/zenpy/lib/api.py", line 270, in _query_zendesk
    return self._get(self._build_url(endpoint=endpoint(*endpoint_args, **endpoint_kwargs)))
  File "/home/netllama/nflx-git/oca-mgmt/venv/lib/python3.7/site-packages/zenpy/lib/endpoint.py", line 300, in __call__
    search_query.insert(0, quote(query))
  File "/home/netllama/.newt-cache/pyenv/versions/3.7.5/lib/python3.7/urllib/parse.py", line 834, in quote
    return quote_from_bytes(string, safe)
  File "/home/netllama/.newt-cache/pyenv/versions/3.7.5/lib/python3.7/urllib/parse.py", line 859, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

Also tried with ```sp = {'type': 'organization', 'id': '9'}``` and that fails in the same way.

**Comment by facetoe** [comment]
Looks like you are using the endpoint incorrectly. You could try, eg:

```python
results = zenpy_client.search("some query", type="organization")
```

However as you are retrieving an organization by id, something like the following is much more efficient:

```python
organization = zenpy_client.organizations(id=9)
```
