### ISSUE TITLE
[Bug] Bulk Destroy Requests URI Length

### ISSUE THREAD

**Issue by amjadtalib** [facetoe/zenpy#385]
Hey @facetoe,

I wanted to flag a bug when using delete many for organization memberships. Not sure why this doesn't happen with the other bulk endpoints I've tested. Also not sure if this is limited to python/requests version, which are:
```
PyDev console: using IPython 5.3.0
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 29 2018, 17:49:27) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Zenpy version 2.0.10
Requests version 2.21.0
```

#### Response Stdout
```
reply: 'HTTP/1.1 414 URI Too Long\r\n'
header: Date: Tue, 17 Dec 2019 22:40:22 GMT
header: Transfer-Encoding: chunked
header: Connection: keep-alive
header: CF-Cache-Status: DYNAMIC
header: Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
header: Server: cloudflare
```
#### Stack Trace
```
Traceback (most recent call last):
  File "/Users/amjad/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-4d55957d130b>", line 17, in <module>
    entity_func.delete(entities)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/api.py", line 465, in delete
    return CRUDRequest(self).delete(api_objects)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/request.py", line 110, in delete
    response = self.api._delete(url, payload=payload)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/api.py", line 124, in _delete
    response = self._call_api(self.session.delete, url, json=payload, timeout=self.timeout)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/api.py", line 149, in _call_api
    response = http_method(url, **kwargs)
  File "/Users/amjad/lib/python2.7/site-packages/requests/sessions.py", line 615, in delete
    return self.request('DELETE', url, **kwargs)
  File "/Users/amjad/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/amjad/lib/python2.7/site-packages/requests/sessions.py", line 686, in send
    r.content
  File "/Users/amjad/lib/python2.7/site-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/Users/amjad/lib/python2.7/site-packages/requests/models.py", line 753, in generate
    raise ChunkedEncodingError(e)
ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```
#### Response Stdout
```
reply: 'HTTP/1.1 414 Request-URI Too Large\r\n'
header: Server: cloudflare
header: Date: Tue, 17 Dec 2019 22:49:29 GMT
header: Content-Type: text/html
header: Content-Length: 175
header: Connection: close
header: CF-RAY: -
```
#### Stack Trace
```
Traceback (most recent call last):
  File "/Users/amjad/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-33-7e3ea98302bf>", line 17, in <module>
    entity_func.delete(entities)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/api.py", line 465, in delete
    return CRUDRequest(self).delete(api_objects)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/request.py", line 110, in delete
    response = self.api._delete(url, payload=payload)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/api.py", line 124, in _delete
    response = self._call_api(self.session.delete, url, json=payload, timeout=self.timeout)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/api.py", line 165, in _call_api
    self._check_response(response)
  File "/Users/amjad/lib/python2.7/site-packages/zenpy/lib/api.py", line 306, in _check_response
    response.raise_for_status()
  File "/Users/amjad/lib/python2.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 414 Client Error: Request-URI Too Large for url: <truncated by amjad for readability>
```
Truncated url: [uri_too_long.txt](https://github.com/facetoe/zenpy/files/3975825/uri_too_long.txt)

**Comment by facetoe** [comment]
I don't think this is a bug in Zenpy/requests, it could be an issue on the network or on Zendesks end. In general though I wouldn't try deleting so many objects in a single request, instead break the work into chunks and send multiple requests.

**Comment by amjadtalib** [comment]
> I don't think this is a bug in Zenpy/requests, it could be an issue on the network or on Zendesks end. In general though I wouldn't try deleting so many objects in a single request, instead break the work into chunks and send multiple requests.

Ah I'm sorry I thought Zenpy handled batching for bulk endpoints, can I turn this into a feature request? No urgency, but would be nice feature for bulk processing.

**Comment by facetoe** [comment]
I've tried to keep Zenpy as a pretty dumb wrapper over the API to keep it simple and easy to maintain. I agree it would be convenient to implement this logic in Zenpy but I think it's best to leave that to the applications.
