### ISSUE TITLE
Issue with search API parameters

### ISSUE THREAD

**Issue by ypperlig** [facetoe/zenpy#397]
Zendesk handles search paramters differently depending on how the value is specified.

For instance:
```python
tickets = client.search(type="ticket", due_date="<1 day", status="<solved")
```

Should be formatted as such:
https://subdomain.zendesk.com/api/v2/search.json?query=type:ticket due_date<1day status<solved

Example query with logging enabled:
```python
DEBUG:urllib3.connectionpool:https://subdomain.zendesk.com:443 "GET /api/v2/search.json?query=type:ticket%20due_date:%22%3C1%20day%22%20status:%3Csolved HTTP/1.1" 422 109

Stacktrace:
Traceback (most recent call last):
  File "audit search.py", line 23, in <module>
    tickets = client.search(type="ticket", due_date="<1 day", status="<solved")
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\zenpy\lib\api.py", line 2140, in __call__
    return self._query_zendesk(self.endpoint, self.object_type, *args, **kwargs)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\zenpy\lib\api.py", line 287, in _query_zendesk
    return self._get(self._build_url(endpoint=endpoint(*endpoint_args, **endpoint_kwargs)))
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\zenpy\lib\api.py", line 129, in _get
    response = self._call_api(self.session.get, url, timeout=self.timeout, **kwargs)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\zenpy\lib\api.py", line 166, in _call_api
    self._check_response(response)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\zenpy\lib\api.py", line 305, in _check_response
    raise APIException(json.dumps(_json), response=response)
zenpy.lib.exception.APIException: {"error": "invalid", "description": "Invalid search: Illegal date value (yyyy-mm-dd expected): due_date:<1 day"}
```

**Comment by facetoe** [comment]
The way you are passing the arguments is incorrect. The following should work:

```python
tickets = zenpy_client.search(type="ticket", due_date_less_than="1 day", status_less_than="solved")
```

The docs contain more info - http://docs.facetoe.com.au/zenpy.html#searching-the-api
