### ISSUE TITLE
RecordNotFoundException when creating articles?

### ISSUE THREAD

**Issue by quinn-p-mchugh** [facetoe/zenpy#527]
Hi there,

I'm having a bit of trouble figuring out how to **create** new articles in my Zendesk instance and am trying to figure out if this is a `zenpy` or a Zendesk issue. Given that [another Zendesk developer came across this issue](https://support.zendesk.com/hc/en-us/community/posts/4991382364570-Trying-to-Post-using-the-APIs) using curl, it seems like this issue isn't isolated to `zenpy`.

Here's my test code. You'll notice that I've listed the name and ID of the `Section`, `ManagmentPermissionGroup`, and `UserSegment` objects to ensure I'm using valid IDs when creating articles.

```
from zenpy import Zenpy
from zenpy.lib.api_objects.help_centre_objects import (
    Article,
    Section,
    ManagementPermissionGroup,
    UserSegment,
)
from pprint import pprint

zenpy_client = Zenpy(
    subdomain="<subdomain>",
    email="<email>",
    token="<token>",
)

pprint("Sections")
sections: list[Section] = zenpy_client.help_center.sections(local="en-us")
for section in sections:
    pprint(section.name)
    pprint(section.id)

pprint("Management Permission Groups")
perm_groups: list[
    ManagementPermissionGroup
] = zenpy_client.help_center.permission_groups()
for perm_group in perm_groups:
    pprint(perm_group.name)
    pprint(perm_group.id)

pprint("User Segment")
user_segments: list[UserSegment] = zenpy_client.help_center.user_segments()
for user_segment in user_segments:
    pprint(user_segment.name)
    pprint(perm_group.id)

zenpy_client.help_center.articles.create(
    section=9422677444891,
    article=Article(
        user_segment_id=9353204464539,
        permission_group_id=4406590189851,
    ),
)
```

When the `zenpy_client.help_center.articles.create(...)` is executed, it calls the `self.api._post` method in `request.py` with the following arguments:

1. `url` = 'https://<my_subdomain>.zendesk.com/api/v2/help_center/sections/9422677444891/articles.json'
2. `payload` = `{'article': {'body': '<h1>Test Body</h1>', 'draft': True, 'id': None, 'permission_group_id': 4406590189851, 'title': 'Test Article', 'user_segment_id': 9353204464539}}`

This seems to be a valid Zendesk API call. **Any ideas on what might be going wrong?**

Full traceback is below:
```
Traceback (most recent call last): 
  File "C:\Users\Quinn McHugh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Quinn McHugh\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code      
    exec(code, run_globals)
  File "c:\Users\Quinn McHugh\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Quinn McHugh\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Quinn McHugh\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Quinn McHugh\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\Quinn McHugh\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Quinn McHugh\.vscode\extensions\ms-python.python-2022.18.2\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Users\Quinn McHugh\Documents\Programming\swagger-to-zendesk-article-generator\src\__main__.py", line 57, in <module>
    zenpy_client.help_center.articles.create(
  File "C:\Users\Quinn McHugh\AppData\Local\Programs\Python\Python310\lib\site-packages\zenpy\lib\util.py", line 111, in inner
    return func(*new_args, **new_kwargs)
  File "C:\Users\Quinn McHugh\AppData\Local\Programs\Python\Python310\lib\site-packages\zenpy\lib\api.py", line 2089, in create
    return CRUDRequest(self).post(article, create=True, id=section)
  File "C:\Users\Quinn McHugh\AppData\Local\Programs\Python\Python310\lib\site-packages\zenpy\lib\request.py", line 81, in post
    return self.api._post(url, payload)
  File "C:\Users\Quinn McHugh\AppData\Local\Programs\Python\Python310\lib\site-packages\zenpy\lib\api.py", line 85, in _post
    response = self._call_api(self.session.post,
  File "C:\Users\Quinn McHugh\AppData\Local\Programs\Python\Python310\lib\site-packages\zenpy\lib\api.py", line 153, in _call_api
    self._check_response(response)
  File "C:\Users\Quinn McHugh\AppData\Local\Programs\Python\Python310\lib\site-packages\zenpy\lib\api.py", line 301, in _check_response
    raise RecordNotFoundException(json.dumps(_json),
zenpy.lib.exception.RecordNotFoundException: {"error": "RecordNotFound", "description": "Not found"}
```

**Comment by quinn-p-mchugh** [comment]
I figured out what I was doing wrong - I used a `permission group ID` for the `user segment ID`. Working code is provided below:

```from zenpy import Zenpy
from zenpy.lib.api_objects.help_centre_objects import (
    Article,
    Section,
    ManagementPermissionGroup,
    UserSegment,
)
from pprint import pprint

zenpy_client = Zenpy(
    subdomain="<subdomain>",
    email="<email>",
    token="<token>",
)

pprint("Sections")
sections: list[Section] = zenpy_client.help_center.sections(local="en-us")
for section in sections:
    pprint(section.name)
    pprint(section.id)

pprint("Management Permission Groups")
perm_groups: list[
    ManagementPermissionGroup
] = zenpy_client.help_center.permission_groups()
for perm_group in perm_groups:
    pprint(perm_group.name)
    pprint(perm_group.id)

pprint("\nUser Segment")
user_segments: list[UserSegment] = zenpy_client.help_center.user_segments()
for user_segment in user_segments:
    pprint(user_segment.name)
    pprint(user_segment.id)

zenpy_client.help_center.articles.create(
    section=9353507199899,
    article=Article(
        body="<h1>Test Body</h1>",
        locale="en-us",
        permission_group_id=9353204464539,
        title="Test Article",
        user_segment_id=4406582131611,
    ),
)

**Comment by sionsmith** [comment]
Saved me hours of debugging!!

**Comment by quinn-p-mchugh** [comment]
@sionsmith 
Wonderful to hear! Thanks for the note. :)
