### ISSUE TITLE
Ticket cannot be rated

### ISSUE THREAD

**Issue by akalex** [facetoe/zenpy#594]
There is some endpoint mapping gap. When I try to rate the ticket, I get `AttributeError`.
```
>>> client.tickets.rate(9535, satisfaction_rating)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/zenpy/lib/api.py", line 679, in rate
    return RateRequest(self).post(rating, id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/akalex/venvs/ticket_hub/lib/python3.11/site-packages/zenpy/lib/request.py", line 178, in post
    self.api.endpoint.satisfaction_ratings(*args))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PrimaryEndpoint' object has no attribute 'satisfaction_ratings'
>>> satisfaction_rating.__class__
<class 'zenpy.lib.api_objects.SatisfactionRating'>
```
Could you please take a look at?

**Comment by cryptomail** [comment]
Terribly sorry that this has occurred.  I will do my best to triage this issue and ensure we have remediation soon.
Thank you for your patience.

**Comment by cryptomail** [comment]
lol are the arguments transposed? My goodness this is weird.  Have a look at this line:
https://github.com/facetoe/zenpy/blob/99aa26276551dbf63b09f7e9e7bc15db442fd73d/zenpy/lib/api.py#L727
That's expecting id, rating, but then RateRequest transposes things into request,id.  I wonder if that's a contributing factor.
Just guessing....doing more investigation.

**Comment by akalex** [comment]
Hey @cryptomail,
Thanks for looking into it, I appreciate your help.

**Comment by cryptomail** [comment]
I think you want this...you want to CREATE a rating for the ticket right?
Try this:
```
zenpy_client = Zenpy(**creds)

satisfaction_rating = SatisfactionRating(ticket_id=1)
rating_response = zenpy_client.satisfaction_ratings.create(1, satisfaction_rating)
print(rating_resonse.__dict__)
```
Did that work?

**Comment by akalex** [comment]
You are absolutely correct. I want to be able to rate a ticket.
Let me try this out.

**Comment by akalex** [comment]
> I think you want this...you want to CREATE a rating for the ticket right? Try this:
> 
> ```
> zenpy_client = Zenpy(**creds)
> 
> satisfaction_rating = SatisfactionRating(ticket_id=1)
> rating_response = zenpy_client.satisfaction_ratings.create(1, satisfaction_rating)
> print(rating_resonse.__dict__)
> ```
> 
> Did that work?
> 
> You'll have to give it a proper rating etc...but try that avenue of write operation if that's what you're after.

It works. Thanks for helping me out with it.
