### ISSUE TITLE
Retry-After Leads to Error

### ISSUE THREAD

**Issue by apodolny** [facetoe/zenpy#62]
When zenpy gets a retry-after response from the server, it seems to wait the appropriate number of seconds and then immediately throws an error:

`WARNING:zenpy.lib.api:Waiting for requested retry-after period: 8 seconds
Traceback (most recent call last):
  File "random_forest_web.py", line 84, in <module>
    new_tickets = zp.tickets.incremental(start_time=last_result_time)
  File "/anaconda/lib/python2.7/site-packages/zenpy/lib/api.py", line 457, in incremental
    return self._get_items(self.endpoint.incremental, self.object_type, start_time=start_time)
  File "/anaconda/lib/python2.7/site-packages/zenpy/lib/api.py", line 83, in _get_items
    return self._get_paginated(endpoint, object_type, *args, **kwargs)
  File "/anaconda/lib/python2.7/site-packages/zenpy/lib/api.py", line 104, in _get_paginated
    _json = self._query(endpoint=endpoint(*args, **kwargs))
  File "/anaconda/lib/python2.7/site-packages/zenpy/lib/api.py", line 108, in _query
    response = self._get(self._get_url(endpoint=endpoint))
  File "/anaconda/lib/python2.7/site-packages/zenpy/lib/api.py", line 46, in _get
    return self._call_api(self.session.get, url)
  File "/anaconda/lib/python2.7/site-packages/zenpy/lib/api.py", line 61, in _call_api
    response = http_method.get(url, **kwargs)
AttributeError: 'function' object has no attribute 'get'`

**Comment by facetoe** [comment]
Thanks for the bug report. This is a regression introduced a few months ago, I'll fix it tonight and push an updated package.

**Comment by facetoe** [comment]
Thanks again for the report @apodolny, let me know if you run into any further issues with the latest version (1.1.2).
