### ISSUE TITLE
Bug while deleting multiple organizations

### ISSUE THREAD

**Issue by umazhar-cond** [facetoe/zenpy#659]
I am getting a below bug while deleting multiple organizations using external ids. I have already cross verified my list of external ids which don't contain None.  This is how I am invoking the delete function, 

**zenpy_client.organizations.delete(orgs_api_objects, destroy_many_external=True)**

**Bug:** 
Traceback (most recent call last):
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/zenpy/lib/api.py", line 388, in _check_response
    _json = response.json()
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Invalid \X escape sequence '\\': line 4 column 102 (char 150)

Traceback (most recent call last):
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/app/sf.py", line 189, in <module>
    main()
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/app/sf.py", line 162, in main
    create_organization(zenpy_client, accounts, batch_size)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/app/sf.py", line 145, in create_organization
    status = zenpy_client.organizations.delete(orgs, destroy_many_external=destroy_ids)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/zenpy/lib/api.py", line 635, in delete
    return CRUDRequest(self).delete(api_objects)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/zenpy/lib/request.py", line 115, in delete
    response = self.api._delete(url, payload=payload)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/zenpy/lib/api.py", line 177, in _delete
    timeout=self.timeout)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/zenpy/lib/api.py", line 227, in _call_api
    self._check_response(response)
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/zenpy/lib/api.py", line 402, in _check_response
    response.raise_for_status()
  File "/Users/usamamazhar/PycharmProjects/cdp-data-lake-consumer/venv/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://(subdomain).zendesk.com/api/v2/organizations/destroy_many.json?ids=None,None,None,None,None

**Comment by cryptomail** [comment]
what version are you currently on @umazhar-cond

**Comment by umazhar-cond** [comment]
zenpy==2.0.49

**Comment by umazhar-cond** [comment]
It was strange to me as I was passing external_ids rather than ids.

**Comment by cryptomail** [comment]
Yes...which is why at this point I will try to repro myself because something is bewitched and not obeying the code I seemingly have in front of me. :)

**Comment by cryptomail** [comment]
I think it may be best to pass the ACTUAL objects and actual organization objects.
You can see that there is an accessor *expecting* external_id to be ON the actual object.
``` if destroy_many_external:
            kwargs['destroy_many_external'] = [
                o.external_id for o in api_objects
            ]
```
is api_objects an array of Organizations?

**Comment by cryptomail** [comment]
If you're passing in external_ids, it won't pass the accessor applied on `o`

**Comment by cryptomail** [comment]
If we feel that this interface is INCORRECT and you want to fast track deletion with passing a flat array of already canonicalized external_ids, then we'll have to talk and think about that :) and make some affordance for it.

**Comment by cryptomail** [comment]
Please comment on the need to pass in objects that are being dereferenced and accessed to the `external_id` field.
If you feel that there needs to be an invocation protocol change, let me know.  Otherwise, I am leaning towards closing this.
