### ISSUE TITLE
search api with type article

### ISSUE THREAD

**Issue by edwardsb** [facetoe/zenpy#84]
`Traceback (most recent call last):
  File "/Users/edwardsb/source/knowbe4/untitled/zendesk_example.py", line 12, in <module>
    for ticket in zenpy.search("adi", type="article", sort_by="created_at"):
  File "/Library/Python/2.7/site-packages/zenpy/lib/api.py", line 175, in __call__
    return self._get_items(self.endpoint, self.object_type, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/zenpy/lib/api.py", line 92, in _get_items
    return self._get_paginated(endpoint, object_type, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/zenpy/lib/api.py", line 113, in _get_paginated
    _json = self._query(endpoint=endpoint(*args, **kwargs))
  File "/Library/Python/2.7/site-packages/zenpy/lib/api.py", line 117, in _query
    response = self._get(self._get_url(endpoint=endpoint))
  File "/Library/Python/2.7/site-packages/zenpy/lib/api.py", line 55, in _get
    return self._call_api(self.session.get, url, timeout=self.timeout)
  File "/Library/Python/2.7/site-packages/zenpy/lib/api.py", line 71, in _call_api
    return self._check_and_cache_response(response)
  File "/Library/Python/2.7/site-packages/zenpy/lib/api.py", line 156, in _check_and_cache_response
    self.object_manager.update_caches(response.json())
  File "/Library/Python/2.7/site-packages/zenpy/lib/manager.py", line 212, in update_caches
    self._cache_search_results(_json)
  File "/Library/Python/2.7/site-packages/zenpy/lib/manager.py", line 236, in _cache_search_results
    cache = self.cache_mapping[object_type]
KeyError: u'article'`

`
from zenpy import Zenpy
zenpy = Zenpy(**zen_creds)

for article in zenpy.search("foo", type="article", sort_by="created_at"):
    print(article)
`

Is there support for searching zendesk articles?

**Comment by facetoe** [comment]
Hi @edwardsb, Zenpy does not currently support articles however I can look at adding support. I'll mark this as a feature requests and look at implementing it as soon as I can.

**Comment by facetoe** [comment]
Hi @edwardsb, Articles are part of the Help Center API which I don't plan on supporting in the near future sorry.
