### ISSUE TITLE
Handle Unexpected AgentMacroReference Event Type (and others)

### ISSUE THREAD

**Issue by samjhecht** [facetoe/zenpy#96]
We're encountering an issue where the process fails because the client does not recognize a new (undocumented) object added by ZD.  According to the response from Zendesk that is conveyed here (https://github.com/cloudbees/zendesk-java-client/issues/126), it's necessary to ensure that the "integration be flexible enough to encounter account unknown event and attribute types without breaking."

Here's an example of the exception we're seeing:
```
Traceback (most recent call last):
  File "/usr/local/bin/sage-zd", line 11, in <module>
    load_entry_point('sage==0.0.1rc0', 'console_scripts', 'sage-zd')()
  File "/usr/local/lib/python2.7/dist-packages/sage/support/zd.py", line 198, in main
    for event in audit.events if event.type in event_types]
  File "/usr/local/lib/python2.7/dist-packages/zenpy/lib/api.py", line 207, in _get_events
    yield self.object_manager.object_from_json(event['type'].lower(), event)
  File "/usr/local/lib/python2.7/dist-packages/zenpy/lib/manager.py", line 182, in object_from_json
    return self.class_manager.object_from_json(object_type, object_json)
  File "/usr/local/lib/python2.7/dist-packages/zenpy/lib/manager.py", line 133, in object_from_json
    obj = self.class_for_type(object_type)
  File "/usr/local/lib/python2.7/dist-packages/zenpy/lib/manager.py", line 138, in class_for_type
    raise ZenpyException("Unknown object_type: " + str(object_type))
zenpy.lib.exception.ZenpyException: Unknown object_type: agentmacroreference
```

p.s. Thanks for providing this client!  Other than this issue, it's been great and has been very helpful!

**Comment by facetoe** [comment]
Hey @samjhecht, are you able to test the commit in #97 and let me know if it works for you? Thanks!
